### PR TITLE
travis builds using cibuildwheel for Linux wheels

### PR DESCRIPTION
**Pull request by mikedh**
Summary
--------
This PR adds linux wheel builds to python-fcl, as discussed in [this trimesh pr](https://github.com/mikedh/trimesh/pull/91). Currently it is [successfully building the wheels](https://travis-ci.org/mikedh/python-fcl/builds/290975769) on [manylinux docker images](https://www.python.org/dev/peps/pep-0513/), across python 2.7, 3.5, and 3.6. It creates the binary wheels using [cibuildwheel](https://github.com/joerick/cibuildwheel) which can then be set to automatically upload the wheels to pypi. The point of this is so that a `pip install python-fcl` will not require the user to have the right build environment including the exactly correct versions of fcl and libccd. As python-fcl develops, the versions of fcl and libccd used in these builds can be updated and checked by travis for compatibility in this repo. OSX and Windows builds aren't set up in this PR, but could be in the future as they are supported by cibuildwheel. 

At the moment the basic build process looks something like
* install gcc
* install cmake 2.8.12 (manylinux1 is centos5 based, which has cmake 2.8.11 which is too old for FCL)
* clone the specific commits of fcl and libccd (in requirements/clone.bash)
* build and install libccd and fcl 
* cibuildwheel builds and packages everything into a wheel for multiple versions of python

Things that still need to be done
--------
* enable travis on this repo
* set up [.travis.yml for automatic pypi deployment](https://github.com/joerick/cibuildwheel-autopypi-example)
* remember to bump fcl/version.py every time you make a change
* set up builds for OSX (should be pretty similar to manylinux)
* set up windows builds (eesh- maybe not for a while)
* fix or understand why test_pairwise_continuous_collisions is reliably failing. I suppressed it for now. (IE https://travis-ci.org/mikedh/python-fcl/builds/290950906):

    ```
    Python 2.7
    
    FAIL: test_pairwise_continuous_collisions (test_fcl.TestFCL)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
     File "/project/test/test_fcl.py", line 129, in test_pairwise_continuous_collisions
     self.assertTrue(result.is_collide)
    AssertionError: False is not true
    ```

### CODE REVIEW

**Comment by mmatl** [comment]
This is awesome, man! :) This is a huge help. I'll take a look at the pairwise continuous collisions bug today or tomorrow. Otherwise, is this pretty much ready to merge?

**Comment by mikedh** [comment]
Haha thanks! Yeah this should be good to merge, the travis builds were succeeding on my fork. In the travis logs it looked like cibuildwheel was also finding all the shared libraries it should have (libccd and libfcl) and putting them in the wheel too, which is kind of impressive. 

It was definitely quite the journey of self discovery. Though once I started doing the local test builds with the docker image instead of committing and waiting half an hour for travis to fail on something dumb it got a lot easier. If you're playing around with it I'd highly recommend testing locally 😛

**Comment by mmatl** [comment]
Will do, I'll let you know if any local tests fail :) Thanks a million for this, man! Also, I went ahead and added you as a contributor, so you'll have write access and such.

Best,
Matt

**Comment by mikedh** [comment]
No problem! And thanks for setting up the auto deploy and travis so quickly! Watching the build upload the wheels automatically was pretty glorious.

I just installed FCL on my laptop through the wheels on pypi, they worked like a champ, tests in fcl / trimesh.test_collisions both looked good.

**Comment by mmatl** [comment]
Awesome, great to hear! This'll be a huge help for easing installs. I'll look at adding OS X builds as soon as I have time as well :)

**Pull request merged**
