### PR TITLE
Bump CIBuildWheel Version to 2.15.0

### PR DESCRIPTION
**Pull request by Eric-Vin**
To address Issue https://github.com/BerkeleyAutomation/python-fcl/issues/69

### CODE REVIEW

**Comment by mikedh** [comment]
Thanks for the PR! Can you bump `version.py` too for the release process?

**Comment by Eric-Vin** [comment]
Done! I went with the most minor version increment but let me know if you'd like something else.

**Comment by mikedh** [comment]
Thanks for the fixes!! Sorry I'd fix these locally but I don't have the project open. I think to fix the build we need to:

- In pyproject.toml change `Cython` -> `Cython<3` from #67 
- locally run `pip install --upgrade black` and run the latest version of `black` on the tests (and/or pin the version of `black` in the github actions YAML).

**Comment by Eric-Vin** [comment]
No problem at all, thank you for your help! I cloned the repo and made the changes you requested, and it looks like the wheels build with `pip wheel ./ --no-deps -w wheelhouse/`, at least on Linux.

**Comment by mikedh** [comment]
Looks close! It seems like everything *except* 3.12 is working, which appears to be surfacing a bug/deprecation in setuptools? Looks like it's this one: https://github.com/pypa/setuptools/issues/3935

**Comment by Eric-Vin** [comment]
Ah yep, distutils is deprecated in 3.12 according to https://peps.python.org/pep-0632/. Unfortunately I'm not really sure how to fix this one.

**Comment by mikedh** [comment]
Yeah 🥲. I think we're blocked until https://github.com/numpy/numpy/issues/23808 gets fixed?

**Comment by mikedh** [comment]
Oh actually this looks like it could plausibly work: 
https://github.com/numpy/numpy/issues/23808#issuecomment-1677596759

```
[build-system]
requires = [
  'numpy; python_version<"3.12"',
  'numpy>=1.26.0b1; python_version>="3.12"',
  # ...
]
```

**Comment by Eric-Vin** [comment]
Seems to work in 3.12 now! Hopefully the actions pass and it hasn't broken anything for older versions (the changes shouldn't from what I can tell).

**Comment by mikedh** [comment]
Looks like it's building now, only failing on 3.12 tests :laughing:. Thanks for all the followup on this PR!

It's a little suspicious python-fcl currently only has numpy in the build-system (which I don't know if the install respects?) I suspect it might need the version-locked numpy in `project.dependencies` too:

```
[project]
name = "python-fcl"
dependencies = ["numpy ...version-info-here"]

```

**Comment by Eric-Vin** [comment]
Ah good point. With this change I can now install properly in 3.12, so hopefully it'll fix the problem.

**Comment by Eric-Vin** [comment]
Shoot now it looks like there's a mismatch....

**Comment by mikedh** [comment]
Oh I wonder if this version range needs something for Python 3.6, or to drop Python 3.6. FWIW I've had to drop 3.6 on other projects due to `pyproject.toml` support and it would probably be fine to do that here if necessary. 

> ERROR: Some build dependencies for file:///project conflict with the backend dependencies: numpy==1.13.3 is incompatible with numpy>=1.26.0b1; python_version >= "3.12".

**Comment by Eric-Vin** [comment]
Hmm I would think it would just work, since for older versions like 3.6 it should fall back to `oldest-supported-numpy`. I wonder if it'll work if I change `oldest-supported-numpy` back to `numpy` in `setup.cfg`, since that's what it was originally.

**Comment by mikedh** [comment]
Oh looking at the logs my theory on this is that we're double-specifying the build system in both `setup.cfg` and `pyproject.toml`:

- `setup.cfg` is used on Python 3.6, and specified in `setup_requires`
- `pyproject.toml` is used on Python 3.7+ and is specified in build

**Comment by Eric-Vin** [comment]
Hmm, so does that mean we would want something like this?

```
setup_requires =
    numpy
    Cython
install_requires =
    numpy; python_version<'3.12'
    numpy>=1.26.0b1; python_version>='3.12'
    Cython
```

Since if we take the numpy specification out of both blocks in `setup.cfg` we'd get back to an earlier version which also had a crash.

**Comment by mikedh** [comment]
Looks like you got it great work! Thanks for the follow ups, these CI changes are particularly rough haha. I think at some point this project should probably use `ini2toml` to move everything from setup.cfg to pyproject.toml and drop 3.6 which would probably make this build a lot more stable.

**Comment by Eric-Vin** [comment]
Great! Thanks for guiding me through the process and for maintaining the project!

**Pull request merged**
