### PR TITLE
Upgrade to FCL 0.7.0

### PR DESCRIPTION
**Pull request by mjd3**
Updated for newer versions of FCL and OctoMap; fixes script for Windows so that CI can build from source. Should resolve the remaining issues in #44.

### CODE REVIEW

**Comment by mjd3** [comment]
Yup should be self-contained now! I think yours was really close already; a lot of this is a mirror of that with some minor changes here and there.

**Review by mikedh — APPROVED** [review]
Looks good to me! Installed and tested fine on Linux.

**Comment by mikedh** [comment]
My only “put” is related to the `install_linux`: it’s currently checking out your copy of FCL master, once this builds should it lock to a commit or release? I see the upstream fcl is pretty dead (they very infrequently merge PR’s these days) so going off a fork sounds good to me.

**Comment by mjd3** [comment]
Thanks so much for the quick review @mikedh, updated wheels for 0.6.11 and 0.7.0 are now on pypi!

**Pull request merged**
